spring.application.name=shipping-service

server.servlet.context-path=/shipping
server.port=9012

spring.datasource.url=jdbc:postgresql://localhost:5432/shippingdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#eureka properties
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
#eureka.instance.ip-address=127.0.0.1
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}